---
  language: objective-c
  before_install:
    - brew update
    - brew uninstall xctool && brew install https://raw.github.com/fpotter/homebrew/246a1439dab49542d4531ad7e1bac7048151f601/Library/Formula/xctool.rb
    - gem install cocoapods -v 0.24.0
    - pod install
  script: "xctool -find-target IGSearchTests test"